version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
      - redis_config:/usr/local/etc/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - ecommerce-network

  # Application logs volume
  app-logs:
    image: busybox
    volumes:
      - app_logs:/logs
    command: tail -f /dev/null

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
  
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  
  postgres_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backups/postgres
  
  redis_config:
    driver: local
  
  app_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

networks:
  ecommerce-network:
    driver: bridge
